## **Librerías**

In [3]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

## **Datos**

In [4]:
df = pd.read_excel("./data/MM 2026wk15.xlsx")
df

,Company,Hiring Status,Open Jobs,Employees,Layoffs (Past 2yr) - People,Layoffs (Past 2yr) - Events
0,Amazon,Hiring,16111,1580000,33700,18
1,Apple,Hiring,6279,150000,714,3
2,Microsoft,Hiring,2428,230000,22853,18
3,Google,Hiring,3561,190000,1293,17
4,Meta,Hiring,860,80000,6734,15
5,NVIDIA,Hiring,1934,36000,0,0
6,Tesla,Hiring,5621,130000,14000,3

In [12]:
df.columns = [col.replace(" ", "_").lower() for col in df.columns]

In [15]:
df.rename({
    'layoffs_(past_2yr)_-_people': 'layoffs_people',
    'layoffs_(past_2yr)_-_events': 'layoffs_events'
    }, axis=1, inplace=True)
df

,company,hiring_status,open_jobs,employees,layoffs_people,layoffs_events,%_open_jobs,%_employees
0,Amazon,Hiring,16111,1580000,33700,18,43.79,65.94
1,Apple,Hiring,6279,150000,714,3,17.07,6.26
2,Microsoft,Hiring,2428,230000,22853,18,6.60,9.60
3,Google,Hiring,3561,190000,1293,17,9.68,7.93
4,Meta,Hiring,860,80000,6734,15,2.34,3.34
5,NVIDIA,Hiring,1934,36000,0,0,5.26,1.50
6,Tesla,Hiring,5621,130000,14000,3,15.28,5.43

In [16]:
df['%_open_jobs'] = df['open_jobs'].apply(lambda x: round(x / df['open_jobs'].sum()*100, 2))
df['%_employees'] = df['employees'].apply(lambda x: round(x / df['employees'].sum()*100, 2))
df['%_layoffs_people'] = df['layoffs_people'].apply(lambda x: round(x / df['layoffs_people'].sum()*100, 2))

In [17]:
df['%_open_jobs_company'] = round(df['open_jobs'] / df['employees'] * 100, 2)
df['%_layoffs_people_company'] = round(df['layoffs_people'] / df['employees'] * 100, 2)
df.sort_values('employees', ascending=False)

,company,hiring_status,open_jobs,employees,layoffs_people,layoffs_events,%_open_jobs,%_employees,%_layoffs_people,%_open_jobs_company,%_layoffs_people_company
0,Amazon,Hiring,16111,1580000,33700,18,43.79,65.94,42.50,1.02,2.13
2,Microsoft,Hiring,2428,230000,22853,18,6.60,9.60,28.82,1.06,9.94
3,Google,Hiring,3561,190000,1293,17,9.68,7.93,1.63,1.87,0.68
1,Apple,Hiring,6279,150000,714,3,17.07,6.26,0.90,4.19,0.48
6,Tesla,Hiring,5621,130000,14000,3,15.28,5.43,17.66,4.32,10.77
4,Meta,Hiring,860,80000,6734,15,2.34,3.34,8.49,1.08,8.42
5,NVIDIA,Hiring,1934,36000,0,0,5.26,1.50,0.00,5.37,0.00

In [18]:
df['diff'] = df['%_layoffs_people_company'] - df['%_open_jobs_company']

In [19]:
df.to_csv('./data/MM_2026wk15.csv', index=False)