## **Librerías**

In [1]:
import pandas as pd
import numpy as np

In [2]:
import plotly.express as px
import plotly.graph_objects as go

## **Datos**

In [3]:
df = pd.read_excel('./data/2024 Democracy Index.xlsx')

In [4]:
df.columns = [col.replace(' ', '_').lower() for col in df.columns]

In [5]:
df.sample(5)

,entity,code,world_region_according_to_owid,year,democracy_index,regime_classification_number,regime_classification,civil_liberties_index,democratic_culture_index,electoral_pluralism_index,functioning_government_index,political_participation_index
267,Bolivia,BOL,South America,2020,5.08,1,Hybrid regime,5.88,3.75,6.08,3.57,6.11
872,Ethiopia,ETH,Africa,2013,3.83,0,Authoritarian regime,4.41,5.63,0.00,3.57,5.56
950,Gabon,GAB,Africa,2023,2.18,0,Authoritarian regime,2.94,3.75,0.83,1.14,2.22
884,Fiji,FJI,Oceania,2006,5.66,1,Hybrid regime,8.24,5.00,6.50,5.21,3.33
2666,Ukraine,UKR,Europe,2022,5.42,1,Hybrid regime,4.41,6.25,6.50,2.71,7.22

In [6]:
df.groupby('year').count()[['entity']]

      entity
year
2006     167
2008     167
2010     167
2011     167
2012     167
2013     167
2014     167
2015     167
2016     167
2017     167
2018     167
2019     167
2020     167
2021     167
2022     167
2023     167
2024     167

In [7]:
df.query('year==2024').groupby('world_region_according_to_owid').agg({
    'entity': ['count'],
    'democracy_index': ['mean', 'median', 'min', 'max']
})

                               entity democracy_index
                                count            mean median   min   max
world_region_according_to_owid
Africa                             50        3.916600  3.465  1.18  8.23
Asia                               47        4.063404  3.280  0.25  8.78
Europe                             40        7.410500  7.740  1.99  9.81
North America                      14        5.642143  5.970  2.09  8.69
Oceania                             4        7.455000  7.410  5.39  9.61
South America                      12        6.009167  6.230  2.25  8.67

In [8]:
df.query('year==2006').groupby('world_region_according_to_owid').agg({
    'entity': ['count'],
    'democracy_index': ['mean', 'median', 'min', 'max']
})

                               entity democracy_index
                                count            mean median   min   max
world_region_according_to_owid
Africa                             50        4.109400  3.770  1.61  8.04
Asia                               47        4.378936  3.920  1.03  8.15
Europe                             40        7.749250  7.850  3.34  9.88
North America                      14        6.566429  6.460  3.52  9.07
Oceania                             4        7.575000  7.775  5.66  9.09
South America                      12        6.520000  6.280  5.42  7.96

In [16]:
index_by_region_and_year = df.groupby(['world_region_according_to_owid', 'year']).agg({
    'democracy_index': ['mean', 'median']
}).reset_index()

In [17]:
index_by_region_and_year.to_csv('data/index_by_region_and_year.csv', index=False)