## **Librerías**

In [4]:
import pandas as pd
import numpy as np

## **Datos**

In [8]:
df = pd.read_excel('./data/raw/MM 2026wk16.xlsx')

In [9]:
df.head()

,#,Occupation,Risk,Wage,Employment,Category
0,1,Telemarketers,96,34000,66430,Highest Risk
1,2,Data Entry Keyers,95,40000,135280,Highest Risk
2,3,"Switchboard Operators, Including Answering Ser...",92,38000,35730,Highest Risk
3,4,Order Clerks,90,45000,83420,Highest Risk
4,5,Telephone Operators,89,39000,3950,Highest Risk

In [17]:
df.groupby(['Category']).agg({
    'Wage': ['count', 'mean', 'median'],
    'Employment': ['count', 'mean', 'median'],

}).round(2)

              Wage                     Employment
             count       mean   median      count       mean    median
Category
Highest Risk    15   42600.00  42000.0         15  137694.67   66430.0
Lowest Risk     15  102733.33  82000.0         15  534109.33  210340.0